default_agent: example_a3_agent_core
agents:
  example_a3_agent_core:
    name: example_a3_agent_core
    language: typescript
    node_version: '20'
    entrypoint: /Users/stanley/GenUI/a3/example_agent_core/agent_core_entry.ts
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: docker
    source_path: /Users/stanley/GenUI/a3/example_agent_core
    aws:
      execution_role: arn:aws:iam::961341517387:role/AmazonBedrockAgentCoreSDKRuntime-us-west-2-d7a850bbc1
      execution_role_auto_create: false
      account: '961341517387'
      region: us-west-2
      ecr_repository: 961341517387.dkr.ecr.us-west-2.amazonaws.com/bedrock-agentcore-example_a3_agent_core
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: example_a3_agent_core-BCKClD8srr
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:961341517387:runtime/example_a3_agent_core-BCKClD8srr
      agent_session_id: e8d6f127-d180-41ff-a4c7-e1e80c3d64e7
    codebuild:
      project_name: bedrock-agentcore-example_a3_agent_core-builder
      execution_role: arn:aws:iam::961341517387:role/AmazonBedrockAgentCoreSDKCodeBuild-us-west-2-d7a850bbc1
      source_bucket: bedrock-agentcore-codebuild-sources-961341517387-us-west-2
    memory:
      mode: STM_AND_LTM
      memory_id: example_a3_agent_core_mem-15dAHMA2D6
      memory_arn: arn:aws:bedrock-agentcore:us-west-2:961341517387:memory/example_a3_agent_core_mem-15dAHMA2D6
      memory_name: example_a3_agent_core_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: true
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
