import type { Config } from 'jest'

export const baseConfig: Config = {
  preset: 'ts-jest/presets/default-esm',
  extensionsToTreatAsEsm: ['.ts', '.tsx'],
  injectGlobals: true,
  transform: {
    '^.+\\.tsx?$': [
      'ts-jest',
      {
        useESM: true,
        tsconfig: {
          baseUrl: '.',
          paths: {
            '@agents': ['./agents'],
            '@agents/*': ['./agents/*'],
            '@constants': ['./src/constants'],
            '@constants/*': ['./src/constants/*'],
            '@core': ['./src/core'],
            '@core/*': ['./src/core/*'],
            '@prompts': ['./src/prompts'],
            '@prompts/*': ['./src/prompts/*'],
            '@providers': ['./src/providers'],
            '@providers/*': ['./src/providers/*'],
            '@skills': ['./src/skills'],
            '@skills/*': ['./src/skills/*'],
            '@stores': ['./src/stores'],
            '@stores/*': ['./src/stores/*'],
            '@utils': ['./src/utils'],
            '@utils/*': ['./src/utils/*'],
            types: ['./src/types'],
            'types/*': ['./src/types/*'],
          },
        },
      },
    ],
    '^.+\\.jsx?$': [
      'ts-jest',
      {
        useESM: true,
      },
    ],
  },
  transformIgnorePatterns: ['/node_modules/(?!(@faker-js|@testing-library)/)', '^.+\\.module\\.(css|sass|scss)$'],
  moduleNameMapper: {
    '^(\\.{1,2}/.*)\\.js$': '$1',
    '^jest\\.setup$': '<rootDir>/jest.setup.ts',
    '^@agents$': '<rootDir>/agents',
    '^@agents/(.*)$': '<rootDir>/agents/$1',
    '^@constants$': '<rootDir>/src/constants',
    '^@constants/(.*)$': '<rootDir>/src/constants/$1',
    '^@core$': '<rootDir>/src/core',
    '^@core/(.*)$': '<rootDir>/src/core/$1',
    '^@prompts$': '<rootDir>/src/prompts',
    '^@prompts/(.*)$': '<rootDir>/src/prompts/$1',
    '^@providers$': '<rootDir>/src/providers',
    '^@providers/(.*)$': '<rootDir>/src/providers/$1',
    '^@stores$': '<rootDir>/src/stores',
    '^@stores/(.*)$': '<rootDir>/src/stores/$1',
    '^@skills$': '<rootDir>/src/skills',
    '^@skills/(.*)$': '<rootDir>/src/skills/$1',
    '^@stores$': '<rootDir>/src/stores',
    '^@stores/(.*)$': '<rootDir>/src/stores/$1',
    '^@utils$': '<rootDir>/src/utils',
    '^@utils/(.*)$': '<rootDir>/src/utils/$1',
    '^types$': '<rootDir>/src/types',
    '^types/(.*)$': '<rootDir>/src/types/$1',
    '^@genui-a3/core$': '<rootDir>/src/index',
  },
  collectCoverageFrom: [
    '**/*.{ts,tsx}',
    '!./*',
    '!**/__tests__/**',
    '!**/no_commit/**',
    '!**/node_modules/**',
    '!src/**/index.*',
    '!src/config/**',
    '!src/constants/**',
    '!src/types/**',
  ],
  coverageProvider: 'v8',
  coverageReporters: ['html', 'text'],
  coveragePathIgnorePatterns: [
    '<rootDir>/.next/',
    '<rootDir>/__tests__/',
    '<rootDir>/no_commit/',
    '<rootDir>/node_modules/',
    '<rootDir>/src/constants/',
    '<rootDir>/src/types/',
  ],
  coverageThreshold: {
    global: {
      functions: 2,
      lines: 4,
      statements: 4,
    },
  },
  verbose: true,
  testEnvironment: 'jsdom',
  setupFilesAfterEnv: ['<rootDir>/jest.setup.ts'],
  testPathIgnorePatterns: [
    '<rootDir>/node_modules/',
    '<rootDir>/__tests__/.*/support/',
    '<rootDir>/__tests__/.*/shared/',
    '<rootDir>/no_commit/',
  ],
  testTimeout: 30000,
}
