import path from 'node:path'
import fs from 'fs-extra'

import { PROVIDER_META, type ProviderConfig } from './providers'

export function generateProviderFile(targetDir: string, primaryProvider: string): void {
  const { importPath, factory, models } = PROVIDER_META[primaryProvider]
  const modelsLiteral = models.map((m) => `'${m}'`).join(', ')

  const content = `import { ${factory} } from '${importPath}'
import type { Provider } from '@genui-a3/core'

let _provider: Provider

export function getProvider(): Provider {
  if (!_provider) {
    _provider = ${factory}({
      models: [${modelsLiteral}],
    })
  }
  return _provider
}
`

  fs.outputFileSync(path.join(targetDir, 'app', 'lib', 'provider.ts'), content)
}

export function generateEnvFile(targetDir: string, config: ProviderConfig): void {
  const lines: string[] = ['# Generated by create-genui-a3', '# This file is git-ignored. Do not commit credentials.', '']

  if (config.providers.includes('openai')) {
    lines.push('# OpenAI', `OPENAI_API_KEY=${config.openaiApiKey || ''}`, '')
  }

  if (config.providers.includes('bedrock')) {
    if (config.bedrockAuthMode === 'profile') {
      lines.push('# AWS Bedrock (profile mode)', `AWS_PROFILE=${config.awsProfile || 'default'}`)
    } else {
      lines.push('# AWS Bedrock (access keys)', `AWS_ACCESS_KEY_ID=${config.awsAccessKeyId || ''}`, `AWS_SECRET_ACCESS_KEY=${config.awsSecretAccessKey || ''}`)
    }
    lines.push(`AWS_REGION=${config.awsRegion || 'us-east-1'}`, '')
  }

  fs.writeFileSync(path.join(targetDir, '.env'), lines.join('\n'))
}

export function scaffoldProject(templateDir: string, targetDir: string, projectName: string): void {
  fs.copySync(templateDir, targetDir)

  const pkgJsonPath = path.join(targetDir, 'package.json')
  if (fs.existsSync(pkgJsonPath)) {
    const pkg = fs.readJsonSync(pkgJsonPath) as Record<string, unknown>
    pkg.name = projectName
    delete pkg.private
    fs.writeJsonSync(pkgJsonPath, pkg, { spaces: 2 })
  }

  const gitignoreSrc = path.join(targetDir, '_gitignore')
  if (fs.existsSync(gitignoreSrc)) {
    fs.renameSync(gitignoreSrc, path.join(targetDir, '.gitignore'))
  }
}
