import path from 'node:path'
import fs from 'fs-extra'
import { PROVIDER_META, type ProviderConfig } from '@create-utils/providers'

export function generateProviderFiles(targetDir: string, config: ProviderConfig): void {
  const providersDir = path.join(targetDir, 'app', 'lib', 'providers')

  // Remove unselected provider files
  for (const [key, meta] of Object.entries(PROVIDER_META)) {
    if (!config.providers.includes(key)) {
      const filePath = path.join(providersDir, meta.file)
      if (fs.existsSync(filePath)) fs.unlinkSync(filePath)
    }
  }

  // Generate index.ts barrel
  const primaryMeta = PROVIDER_META[config.primaryProvider]
  const lines: string[] = []

  for (const provKey of config.providers) {
    const meta = PROVIDER_META[provKey]
    const baseName = meta.file.replace('.ts', '')
    lines.push(`export { ${meta.exportName} } from './${baseName}'`)
  }
  lines.push(`export { ${primaryMeta.exportName} as getProvider } from './${primaryMeta.file.replace('.ts', '')}'`)
  lines.push('')

  fs.outputFileSync(path.join(providersDir, 'index.ts'), lines.join('\n'))

  // Remove unselected provider packages from package.json
  const pkgJsonPath = path.join(targetDir, 'package.json')
  if (fs.existsSync(pkgJsonPath)) {
    const pkg = fs.readJsonSync(pkgJsonPath) as Record<string, Record<string, string>>
    for (const [key, meta] of Object.entries(PROVIDER_META)) {
      if (!config.providers.includes(key) && pkg.dependencies?.[meta.npmPackage]) {
        delete pkg.dependencies[meta.npmPackage]
      }
    }
    fs.writeJsonSync(pkgJsonPath, pkg, { spaces: 2 })
  }
}

export function generateEnvFile(targetDir: string, config: ProviderConfig): void {
  const lines: string[] = [
    '# Generated by create-genui-a3',
    '# This file is git-ignored. Do not commit credentials.',
    '',
  ]

  if (config.providers.includes('openai')) {
    lines.push('# OpenAI', `OPENAI_API_KEY=${config.openaiApiKey || ''}`, '')
  }

  if (config.providers.includes('anthropic')) {
    lines.push('# Anthropic', `ANTHROPIC_API_KEY=${config.anthropicApiKey || ''}`, '')
  }

  if (config.providers.includes('bedrock')) {
    if (config.bedrockAuthMode === 'profile') {
      lines.push('# AWS Bedrock (profile mode)', `AWS_PROFILE=${config.awsProfile || 'default'}`)
    } else {
      lines.push(
        '# AWS Bedrock (access keys)',
        `AWS_ACCESS_KEY_ID=${config.awsAccessKeyId || ''}`,
        `AWS_SECRET_ACCESS_KEY=${config.awsSecretAccessKey || ''}`,
      )
    }
    lines.push(`AWS_REGION=${config.awsRegion || 'us-east-1'}`, '')
  }

  fs.writeFileSync(path.join(targetDir, '.env'), lines.join('\n'))
}

export function scaffoldProject(templateDir: string, targetDir: string, projectName: string): void {
  fs.copySync(templateDir, targetDir)

  const pkgJsonPath = path.join(targetDir, 'package.json')
  if (fs.existsSync(pkgJsonPath)) {
    const pkg = fs.readJsonSync(pkgJsonPath) as Record<string, unknown>
    pkg.name = projectName
    delete pkg.private
    fs.writeJsonSync(pkgJsonPath, pkg, { spaces: 2 })
  }

  const gitignoreSrc = path.join(targetDir, '_gitignore')
  if (fs.existsSync(gitignoreSrc)) {
    fs.renameSync(gitignoreSrc, path.join(targetDir, '.gitignore'))
  }

  // Create .cursorrules symlink pointing to CLAUDE.md
  // Using a fallback to copy if symlinks are not supported (e.g. Windows without admin)
  try {
    const cursorrulesPath = path.join(targetDir, '.cursorrules')
    const claudeMdPath = path.join(targetDir, 'CLAUDE.md')
    if (fs.existsSync(claudeMdPath)) {
      fs.symlinkSync('CLAUDE.md', cursorrulesPath, 'file')
    }
  } catch {
    try {
      fs.copyFileSync(path.join(targetDir, 'CLAUDE.md'), path.join(targetDir, '.cursorrules'))
    } catch {
      // Ignore fallback errors
    }
  }
}
