name: Check Version
on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]
  workflow_dispatch:
jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout `package.json`
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Version and Release Setup
        run: |
          version_tag=$(cat package.json | jq -r '.version')

          echo "version_tag=${version_tag}" >> $GITHUB_OUTPUT

          echo "::group::Version Tag"
          echo 'Version Tag: '${version_tag}
          echo "::endgroup::"
        shell: bash
        id: version

      - name: Check for Tag
        run: |
          tag="${{ steps.version.outputs.version_tag }}"

          if git show-ref --tags --verify --quiet "refs/tags/${tag}"; then
              echo "The tag ${tag} already exists, please update the version in 'package.json'."
              exit 1
          fi
          echo "Proceed with PR"
        shell: bash
