name: Publish (create)
on:
  push:
    branches:
      - main
    paths:
      - 'create/**'
  workflow_dispatch:

permissions:
  id-token: write   # required for OIDC with npm
  contents: write   # push tag

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    environment:
      name: main
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: false

      - name: Version and Release Setup
        run: |
          version=$(cat create/package.json | jq -r '.version')
          version_tag="create-${version}"

          echo "version=${version}" >> $GITHUB_OUTPUT
          echo "version_tag=${version_tag}" >> $GITHUB_OUTPUT

          echo "::group::Version Tag"
          echo 'Version Tag: '${version_tag}
          echo "::endgroup::"
        shell: bash
        id: version

      - name: Check for Tag
        run: |
          tag="${{ steps.version.outputs.version_tag }}"

          if git show-ref --tags --verify --quiet "refs/tags/${tag}"; then
              echo "The tag ${tag} already exists, skipping publish."
              exit 1
          fi
          echo "Proceeding with publish."
        shell: bash

      - name: Setup Node JS
        uses: actions/setup-node@v6
        with:
          node-version-file: .tool-versions
          cache: 'npm'
          cache-dependency-path: create/package-lock.json

      - name: Install Dependencies
        run: cd create && npm ci
        shell: bash

      - name: Push new tag
        id: image_tags
        run: |
          version_tag="${{ steps.version.outputs.version_tag }}"

          echo "new_tag=${version_tag}" >> $GITHUB_OUTPUT

          echo "::group::New Tag"
          echo "New Tag: ${version_tag}"
          echo "::endgroup::"

          git tag "${version_tag}"
          git push origin "${version_tag}"

          # Get all tags sorted by version, filtered by the create- prefix
          previous_tag=$(git tag --sort=-v:refname | grep -E "^create-[0-9]+\.[0-9]+\.[0-9]+$" | sed -n '2p')

          echo "previous_tag=${previous_tag}" >> $GITHUB_OUTPUT

          echo "::group::Previous Tag"
          echo "Previous Tag: ${previous_tag}"
          echo "::endgroup::"
        shell: bash

      - name: Create/Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          excludeTypes: ''
          fromTag: ${{ steps.image_tags.outputs.previous_tag != '' && steps.image_tags.outputs.new_tag || '' }}
          includeInvalidCommits: true
          tag: ${{ steps.image_tags.outputs.previous_tag == '' && steps.image_tags.outputs.new_tag || '' }}
          toTag: ${{ steps.image_tags.outputs.previous_tag != '' && steps.image_tags.outputs.previous_tag || '' }}
          token: ${{ github.token }}
          writeToFile: false

      - name: Publish to NPM
        run: cd create && npm publish --access public
        shell: bash

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          body: ${{ steps.changelog.outputs.changes }}
          makeLatest: false
          name: '@genui-a3/create v${{ steps.version.outputs.version }}'
          prerelease: false
          skipIfReleaseExists: true
          tag: ${{ steps.image_tags.outputs.new_tag }}

      - name: Clean up on failure
        if: ${{ failure() && steps.image_tags.outputs.new_tag }}
        run: |
          git push --delete origin "${{ steps.image_tags.outputs.new_tag }}"
        shell: bash
